# Generated by Django 5.2.8 on 2025-11-12 18:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(verbose_name='дата заезда')),
                ('check_out', models.DateField(verbose_name='дата выезда')),
                ('guests', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='количество гостей')),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='общая стоимость')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено'), ('completed', 'Завершено')], default='pending', max_length=20, verbose_name='статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('notes', models.TextField(blank=True, verbose_name='пожелания гостя')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'бронь',
                'verbose_name_plural': 'брони',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название отеля')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='адрес')),
                ('city', models.CharField(max_length=100, verbose_name='город')),
                ('country', models.CharField(max_length=100, verbose_name='страна')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('rating', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)], verbose_name='рейтинг (1-5)')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
            ],
            options={
                'verbose_name': 'отель',
                'verbose_name_plural': 'отели',
                'ordering': ['name'],
                'unique_together': {('name', 'city', 'country')},
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='тип номера')),
                ('capacity', models.PositiveSmallIntegerField(verbose_name='вместимость (чел.)')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена за ночь')),
                ('available_rooms', models.PositiveSmallIntegerField(default=1, verbose_name='кол-во доступных номеров')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='bookings.hotel')),
            ],
            options={
                'verbose_name': 'тип номера',
                'verbose_name_plural': 'типы номеров',
                'unique_together': {('hotel', 'name')},
            },
        ),
        migrations.DeleteModel(
            name='ServiceType',
        ),
        migrations.AddField(
            model_name='booking',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.roomtype'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('check_out__gt', models.F('check_in'))), name='check_out_after_check_in'),
        ),
    ]
